.TH CHOOSE 1 2012-01-23 "" "User Commands"

.SH NAME
choose \- a shell menu

.SH SYNOPSIS

.B choose
.RI [ options ]
.RI < default_choice >
<choice_1> [choice_2] ...

.B choose
.RI [ options ]
.RI [ default_choice ]
< file_of_choices

command_which_print_choices |
.B choose
.RI [ options ]
.RI [ default_choice ]

Input choices can be arguments starting at the second one, a file with a choice per line, or lines from a piped command.

.SH DESCRIPTION

.B choose
allows an interactive choice on stderr among lines from stdin (or arguments) and returns the result on stdout.

            multiple lines            menu            one line
                           --->      choose      --->
             args / stdin      TTY input / stderr      stdout

It is nearly the same goal as the shell builtin
.B select
with fancy I/O more.

If there are many choices, the selected line is validated when the key ENTER is pressed.

The optional argument
.I default_choice
can preselect a line.
In cursor mode, it falls back to the first line if there is no matching default.

.SH OPTIONS
.TP
.B -h
help
.P
The different input behaviours are called modes.
.TP
.B -c
cursor mode (default)
.br
The selection can be moved with the keys UP and DOWN.
.TP
.B -n
numerated mode
.br
A number matching a list item can be entered.
.P
There are 2 styles for the selected line. It can be shown with an arrow or in a reversed font.
.TP
.B -r
reversed style (default)
.TP
.B -a
arrow style
.P
When the choice is done, the menu can disappeared (quiet), be replaced by the chosen line (default), or be kept as is (verbose).
.TP
.B -q
quiet = clean all on exit
.TP
.B -v
verbose = keep menu on exit
.P
If you don't want it tampers your TTY with alternative settings and special characters, use
.RI - nav
options (numerated mode with arrow and keep verbose). It disables all "advanced" features.

.SH ENVIRONMENT
.TP
.B INDENT
is the prefix of each line in cursor mode.
.TP
.B ARROW
begins current line in arrow style.

.SH EXIT STATUS
.TP
.B 0
Successful execution
.TP
.B 1
Syntax error
.TP
.B 2
Interrupted by a signal

.SH BUGS

\(bu In cursor mode, long lines with non printable characters are smaller than the terminal width.

\(bu The cleanup in numerated mode erase not enough lines if there are choices on multiple lines.

\(bu Long lists with more lines than the terminal height are only supported in numerated verbose mode.

.SH EXAMPLE
.nf \f(CW
# answer=$(choose -av '' yes no)
=>  yes
    no
# echo $answer
yes
.fi
