#! /bin/sh -e

# choose-git-branch: checkout local or remote branch
# by Thomas Monjalon
# This file is in the public domain.

. $(dirname $(readlink -m $0))/choose-git-common

BRANCHES=$(git branch | sed 's,no branch,none,')
LOCALS=$(echo "$BRANCHES" | cut -c3-)
CURRENT=$(echo "$BRANCHES" | sed -n 's,^*.,,p')

# remotes not tracked = all - tracked
TRACKABLES=$(printf "$(get_git_all_remotes)\n$(get_git_tracked_remotes)" | sort | uniq -u)

TRACK=${TRACKABLES:+- track a new one -}
CHOICE=$($CHOOSE "$CURRENT" $LOCALS "$TRACK")
CLEAR=$((CLEAR + 1))
[ "$CHOICE" != "$CURRENT" ] || abort 1

if [ "$CHOICE" = "$TRACK" ] ; then
	echo remotes:
	CLEAR=$((CLEAR + 1))
	CHOICE=$($CHOOSE '' $TRACKABLES)
	CLEAR=$((CLEAR + 1))
	BRANCH="--track $CHOICE"
else
	BRANCH=$CHOICE
fi

STASH=false
DIRTY=$(git status --porcelain -uno)
if [ -n "$DIRTY" ] ; then
	echo directory is dirty
	CLEAR=$((CLEAR + 1))
	CHOICE=$($CHOOSE '' '- stash modifications -' '- keep modifications -')
	if echo $CHOICE | grep -q stash ; then
		STASH=true
	fi
fi

! $STASH || git stash --quiet
git checkout --quiet $BRANCH
! $STASH || git stash pop --quiet
